# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
# ------ #
# TILINK #
# ------ #

@rp2.asm_pio()
def TILINK():
    wrap_target()
    label("0")
    jmp("0")                              # 0
    label("1")
    set(y, 7)                             # 1
    irq(wait 0)                           # 2
    label("3")
    jmp(not_osre, "19")                   # 3
    label("4")
    mov(osr, pins)                        # 4
    out(x, 1)                             # 5
    out(null, 32)                         # 6
    jmp(not_x, "12")                      # 7
    jmp(pin, "3")                         # 8
    wait(1, pin, 1)         .side(1)      # 9
    wait(1, pin, 0)         .side(0)      # 10
    jmp("16")                             # 11
    label("12")
    jmp(pin, "14")                        # 12
    jmp("29")                             # 13
    label("14")
    wait(1, pin, 0)         .side(2)      # 14
    wait(1, pin, 1)         .side(0)      # 15
    label("16")
    in_(x, 1)                             # 16
    jmp(y_dec, "4")                       # 17
    jmp("1")                              # 18
    label("19")
    set(y, 7)                             # 19
    label("20")
    out(x, 1)                             # 20
    jmp(not_x, "25")                      # 21
    wait(0, pin, 0)         .side(2)      # 22
    wait(1, pin, 0)         .side(0)      # 23
    jmp("27")                             # 24
    label("25")
    wait(0, pin, 1)         .side(1)      # 25
    wait(1, pin, 1)         .side(0)      # 26
    label("27")
    jmp(x_dec, "20")                      # 27
    jmp("1")                              # 28
    label("29")
    jmp("29")                             # 29
    wrap()


