# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
# ------ #
# TILINK #
# ------ #

@rp2.asm_pio()
def TILINK():
    wrap_target()
    label("0")
    set(y, 7)                             # 0
    label("1")
    mov(x, status)          .side(0)      # 1
    jmp(x_dec, "22")                      # 2
    mov(osr, pins)          .side(0)      # 3
    out(x, 1)                             # 4
    jmp(not_x, "10")                      # 5
    jmp(pin, "1")                         # 6
    label("7")
    wait(1, pin, 1)         .side(1)      # 7
    wait(1, pin, 0)         .side(0)      # 8
    jmp("14")                             # 9
    label("10")
    jmp(pin, "12")                        # 10
    jmp("31")                             # 11
    label("12")
    wait(1, pin, 0)         .side(2)      # 12
    wait(1, pin, 1)         .side(0)      # 13
    label("14")
    in_(x, 1)                             # 14
    jmp(y_dec, "17")                      # 15
    jmp("0")                              # 16
    label("17")
    mov(osr, pins)                        # 17
    out(x, 1)                             # 18
    jmp(not_x, "10")                      # 19
    jmp(pin, "17")                        # 20
    jmp("7")                              # 21
    label("22")
    pull(, block)                         # 22
    label("23")
    out(x, 1)                             # 23
    jmp(not_x, "27")                      # 24
    wait(0, pin, 0)         .side(2)      # 25
    jmp("29")                             # 26
    label("27")
    wait(0, pin, 1)         .side(1)      # 27
    wait(1, pin, 0)         .side(0)      # 28
    label("29")
    wait(1, pin, 1)         .side(0)      # 29
    jmp(y_dec, "23")                      # 30
    wrap()
    label("31")
    jmp("31")                             # 31


