# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
# ------ #
# TILINK #
# ------ #

@rp2.asm_pio()
def TILINK():
    wrap_target()
    label("0")
    mov(osr, pins)          .side(0)      # 0
    out(x, 1)               .side(0)      # 1
    jmp(not_x, "7")         .side(0)      # 2
    jmp(pin, "0")           .side(0)      # 3
    wait(1, pin, 1)         .side(1)      # 4
    wait(1, pin, 0)         .side(0)      # 5
    jmp("11")                             # 6
    label("7")
    jmp(pin, "9")           .side(0)      # 7
    jmp("21")               .side(0)      # 8
    label("9")
    wait(1, pin, 0)         .side(2)      # 9
    wait(1, pin, 1)         .side(0)      # 10
    label("11")
    in_(x, 1)               .side(0)      # 11
    jmp("0")                .side(0)      # 12
    label("13")
    out(x, 1)               .side(0)      # 13
    jmp(not_x, "17")        .side(0)      # 14
    wait(0, pin, 0)         .side(2)      # 15
    jmp("19")               .side(0)      # 16
    label("17")
    wait(0, pin, 1)         .side(1)      # 17
    wait(1, pin, 0)         .side(0)      # 18
    label("19")
    wait(1, pin, 1)         .side(0)      # 19
    jmp("13")                             # 20
    label("21")
    jmp("21")                             # 21
    wrap()


